name: CI

on:
  push:
    branches: [master]
  pull_request: ~

env:
  FORCE_COLOR: 1

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - name: Install prettier
        run: npm ci
      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always
