name: Validate

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-24.04
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
